version: '3'

services:
        mysql-development:
                image: mysql:8.0.17
                environment:
                        MYSQL_ROOT_PASSWORD: 12345
                        MYSQL_DATABASE: zallpydb
                ports:
                        - "3308:3306"

        rabbitmq:
                image: "rabbitmq:3-management"
                hostname: "rabbit"
                ports:
                        - "15672:15672"
                        - "5672:5672"
                labels:
                        NAME: "rabbitmq"
        #    volumes:
        #      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

